<a href="https://colab.research.google.com/github/wendyleosaputra-oss/Tugas-dan-laporan-minggu-ke-8-/blob/main/Latihan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3. Berlanjut memasukan data pada google coolab dari github dan buat la kode program seperti ini
cara masukin data nya tekan file dan upload dari file yang telah di download tadi dan copy path data nya agar bisa di akses oleh google coolab dengan menekan kanan mouse atau laptop dan tekan opsi copy path dan salin lalu di apit kurung agar bisa bekerja

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
wendy_leo_saputra= pd.read_csv('/content/mahasiswa.csv')

4. tulis kode phyton di bawah ini untuk melihat data 5 teratas dan untuk mengetahui data awal

In [ ]:
wendy_leo_saputra.head()
#melihat 5 data teratas

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
0,E0001,Aldi,Teknik,150,59.5,82.0,2024-05-05
1,E0002,Budi,teknik,20.0,84.5,99.0,2024-02-14
2,E0003,Citra,Energi,-5,56.2,78.0,2024-04-29
3,E0004,Dewi,Teknik,twenty,63.0,99.0,2024-08-02
4,E0005,Eka,Manajemen Energi,22.0,999,65.0,2024-03-22

In [ ]:
5. selanjut nya kode phyton di bawah ini untuk melihat data 5 terakhir dan untuk mengetahui data akhir

In [ ]:
wendy_leo_saputra.tail()
#melihat 5 data terakhir

      nim   nama      jurusan  umur nilai_akhir  kehadiran_pct tanggal_daftar
73  E0057  Fauzi       Energi  23.0        58.2           76.0     2024-02-05
74  E0039   Mita       Energi  23.0        77.2           79.0     2024-01-04
75  E0069  Salsa  Informatika  23.0        63.4           86.0     2024-04-14
76  E0031   Eros  Informatika  23.0        68.0           66.0     2024-02-27
77  E0026   Zara  Informatika  24.0        90.4           82.0     2024-11-24

In [ ]:
6. kode phyton ini untuk melihat tipe data dari setiap kolom

In [ ]:
wendy_leo_saputra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nim             78 non-null     object
 1   nama            78 non-null     object
 2   jurusan         76 non-null     object
 3   umur            76 non-null     object
 4   nilai_akhir     76 non-null     object
 5   kehadiran_pct   76 non-null     float64
 6   tanggal_daftar  76 non-null     object
dtypes: float64(1), object(6)
memory usage: 4.4+ KB

7.setelah melakukan langkah langkah tadi masukan kode phyton dibawah ini yang berfungsi untuk mengecek error pada data dan ketika di temukan nya kita akan memperbaiki data nya

In [ ]:
wendy_leo_saputra.isna().sum()

nim               0
nama              0
jurusan           2
umur              2
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

8. masukan kode phyton nya dan kita akan mencari jumlah duplikasi yang ada pada data dan menampilkan pada output nya jumlah nilai yang hilang dan untuk memperbaiki data yang ada duplikasi nya

In [ ]:
print("Jumlah duplikasi: ", wendy_leo_saputra.duplicated().sum())

Jumlah duplikasi:  8

9. Masukan kode phytonnya yang dimana dia berfungsi untuk mengecek jumlah duplikasi pada data

In [ ]:
wendy_leo_saputra.drop_duplicates(inplace=True)
print("Jumlah duplikasi: ", wendy_leo_saputra.duplicated().sum())

Jumlah duplikasi:  0

10. masukan kode phytonnya yang dimana isna.()berfungsi untuk mencari jumlah nilai yang hilang dan .sum()berfungsi sebagai menjumlahkan nilai yang hilang pada data

In [ ]:
wendy_leo_saputra.isna().sum()

nim               0
nama              0
jurusan           2
umur              2
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

11. masukan kode phyton nya dan fungsi nya itu untuk memperbaiki nilai yang hilang pada jurusan yang ada pada data

In [ ]:
wendy_leo_saputra['jurusan'] = wendy_leo_saputra['jurusan'].fillna("Pembangkit Energi")

#di sini untuk jurusan di isi dengan "Pembangkit Energi"

12. dan setelah kita memasukan kode tersebut kita memastikan lagi apakah data pada jurusan sudah di perbaiki atau belum dengan memasukan kode phyton nya

In [ ]:
wendy_leo_saputra.isna().sum()

nim               0
nama              0
jurusan           0
umur              2
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

13. setelah itu kita memperbaiki nilai data yang hilang pada umur dan masukan kode phytonnya ini berfungsi untuk memperbaiki data umur yang hilang

In [ ]:
wendy_leo_saputra['umur'] = wendy_leo_saputra['umur'].fillna(23)

14. kita kembali lagi untuk menngecek apakah data pada umur sudah di perbaiki dengan memasukan kode phyton nya

In [ ]:
wendy_leo_saputra.isna().sum()

nim               0
nama              0
jurusan           0
umur              0
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

15. selanjutnya kira mencari rata rata nilai dan mengkonversi data dengan menjadi float untuk memperbaiki data pada nilai akhir dengan menulis kode phyton ini

In [ ]:
wendy_leo_saputra['nilai_akhir'] = pd.to_numeric(wendy_leo_saputra['nilai_akhir'], errors='coerce') #konversi tipe data menjadi numeric yaitu float

wendy_leo_saputra['nilai_akhir'].mean() #mecari rata-rata

np.float64(88.15384615384616)

16. baru setelah mengetahui nilai nya kita akan mengecek informasi pada data dengan memasukan kode phytonnya

In [ ]:
wendy_leo_saputra.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nim             70 non-null     object
 1   nama            70 non-null     object
 2   jurusan         70 non-null     object
 3   umur            70 non-null     object
 4   nilai_akhir     65 non-null     float64
 5   kehadiran_pct   68 non-null     float64
 6   tanggal_daftar  68 non-null     object
dtypes: float64(2), object(5)
memory usage: 4.4+ KB

17. baru kita memperbaiki data nilai akhir nya dan masukan kode phytonnya

In [ ]:
wendy_leo_saputra['nilai_akhir'] = wendy_leo_saputra['nilai_akhir'].fillna(88)
#sekarang isi missing value pada nilai_akhir dengan nilai rata-rata yg sudah di dapat sebelumnya

18. baru kita mengecek hasil dengan menggunakan kode phyton nya

In [ ]:
wendy_leo_saputra.isna().sum()
#cek hasilnya

nim               0
nama              0
jurusan           0
umur              0
nilai_akhir       0
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

19. dan kita cari lagi nilai rata rata dan bkonversi data menjadi numeric yaitu float dengan memasukan kode phyton nya

In [ ]:
wendy_leo_saputra['kehadiran_pct'] = pd.to_numeric(wendy_leo_saputra['kehadiran_pct'], errors='coerce') #konversi tipe data menjadi numeric yaitu float

wendy_leo_saputra['kehadiran_pct'].mean() #mecari rata-rata

np.float64(82.13235294117646)

20. setelah mengetahui nilai numeric nya kita akan memperbaiki nilai yang yang hilang pada data dengan nilai rata rata yang sudah didapatkan dan masukan kode phyton nya

In [ ]:
wendy_leo_saputra['kehadiran_pct'] = wendy_leo_saputra['kehadiran_pct'].fillna(82)
#sekarang isi missing value pada nilai_akhir dengan nilai rata-rata yg sudah di dapat sebelumnya

21. cek hasil nya dan ternyata nilai kehadiran_pct sudah di perbaiki

In [ ]:
wendy_leo_saputra.isna().sum()
#cek hasilnya

nim               0
nama              0
jurusan           0
umur              0
nilai_akhir       0
kehadiran_pct     0
tanggal_daftar    2
dtype: int64

22. karena data tanggal daftar bertipe string jadi tak perlu lagi mencari nilai numerik nya jadi langsung saja memperbaiki data pada tanggal daftar

In [ ]:
wendy_leo_saputra['tanggal_daftar'] = wendy_leo_saputra['tanggal_daftar'].fillna('2024-03-24')

# karena tanggal daftar di sini bertipe string jadi langsung masukan saja tidak perlu di cari rata-rata nya atau konversi ke numerik

23. cek hasilnya dan lihat dengan menggunakan kode phyton di bawah ini

In [ ]:
wendy_leo_saputra.isna().sum()

nim               0
nama              0
jurusan           0
umur              0
nilai_akhir       0
kehadiran_pct     0
tanggal_daftar    0
dtype: int64

24. selanjut nya kita akan menghitung berapa kali nilai yang muncul dalam data dan mengembalikan hasil dalam bentuk terurut dari yang paling sering muncul dengan memasukan kode phyton di bawah ini

In [ ]:
wendy_leo_saputra.jurusan.value_counts()

jurusan
Energi               21
Informatika          17
Teknik               12
Manajemen Energi     11
Pembangkit Energi     2
teknik                1
 energi               1
ManajemenEnergi       1
EnErGi                1
Teknik                1
ENG                   1
ENERGI                1
Name: count, dtype: int64

25. selanjut nya kita akan menghitung berapa kali nilai yang muncul dalam data dan mengembalikan hasil dalam bentuk terurut dari yang paling sering muncul dengan memasukan kode phyton di bawah ini

In [ ]:
wendy_leo_saputra.umur.value_counts()

umur
23.0          15
25.0          10
20.0           9
24.0           9
22.0           8
19.0           7
21.0           4
23             2
150            1
twenty         1
-5             1
120            1
NaN_string     1
21years        1
Name: count, dtype: int64

26. selanjut nya kita mengubah huruf pada data dengan mengubah nya menjadi huruf kecil dan masukan kode phytonnya

In [ ]:
wendy_leo_saputra['jurusan'] = wendy_leo_saputra['jurusan'].str.lower().str.strip()
#ubah menjadi huruf kecil

27. selanjutnya kita akan mencari tau jurusan yang sering muncul pada data dan masukan kode phyton nya

In [ ]:
wendy_leo_saputra.jurusan.value_counts()

jurusan
energi               24
informatika          17
teknik               14
manajemen energi     11
pembangkit energi     2
manajemenenergi       1
eng                   1
Name: count, dtype: int64

28. selanjutnya kita akan memperbaiki teks yang salah atau typo dengan mapping pada data dan masukan kode phyton nya seperti di bawah ini

In [ ]:
#untuk memudahkan replacing maka di buatkan mapping jurusan sesuai dengan yg di inginkan, dengan kata-kata yg mirip di masukan ke jurusan yg seusai

mapping_jurusan = {
    "energi": "Pembangkit Energi",
    " energi ": "Pembangkit Energi",
    "ENERGI": "Pembangkit Energi",
    "EnErGi": "Pembangkit Energi",
    "eng": "Pembangkit Energi",
    "teknik": "Pembangkit Energi",
    "Teknik ": "Pembangkit Energi",
    "teknik ": "Pembangkit Energi",
    "manajemenenergi": "Manajemen Energi",
    "manajemen energi": "Manajemen Energi"
}

29. setelah itu baru kita memperbaiki data yang ada pada jurusan dengan memasukan kode phyton tadi dan masukan mapping yang telah di buat

In [ ]:
wendy_leo_saputra["jurusan"] = wendy_leo_saputra["jurusan"].replace(mapping_jurusan)

30. baru setelah memperbaiki data pada jurusan kita kembalikan menjadi huruf besar dengan memasukan kode phyton di bawah ini

In [ ]:
wendy_leo_saputra["jurusan"] = wendy_leo_saputra["jurusan"].str.title()

#kembalikan menjadi huruf besar

31. kita lihat hasil nya dengan menggunakan kode phyton nya

In [ ]:
wendy_leo_saputra.jurusan.value_counts()

jurusan
Pembangkit Energi    41
Informatika          17
Manajemen Energi     12
Name: count, dtype: int64

32. setelah itu kita tampilkan pada outputnya dengan fungsi print()

In [ ]:
print("Hasil setelah normalisasi dan pemetaan:")
print(wendy_leo_saputra ['jurusan'].value_counts())

Hasil setelah normalisasi dan pemetaan:
jurusan
Pembangkit Energi    41
Informatika          17
Manajemen Energi     12
Name: count, dtype: int64

33. kita melihat data umur yang sering muncul dengan memasukan kode phyton nya

In [ ]:
wendy_leo_saputra.umur.value_counts()

umur
23.0          15
25.0          10
20.0           9
24.0           9
22.0           8
19.0           7
21.0           4
23             2
150            1
twenty         1
-5             1
120            1
NaN_string     1
21years        1
Name: count, dtype: int64

34. kita mempebaiki data pada umur yang dimana ada twenty menjadi 20 dengan memasukan kode phyton nya bisa dilakukan satu persatu sedangkan tadi sekaligus

In [ ]:
wendy_leo_saputra['umur'] = wendy_leo_saputra['umur'].replace('twenty', 20)

#bisa di lakuakn replace satu persatu seperti ini
# dari sebelumnya twenty menjadi 20

35. selanjutnya kita menampilkan dengan print pada output nya untuk mengecek data umur apakah sudah di perbaiki atau belum

In [ ]:
print(wendy_leo_saputra['umur'].value_counts())

umur
23.0          15
25.0          10
20.0           9
24.0           9
22.0           8
19.0           7
21.0           4
23             2
150            1
20             1
-5             1
120            1
NaN_string     1
21years        1
Name: count, dtype: int64

36. selanjut nya kita sekaligus memperbaiki data dengan umur menggunakan mapping dan masukan kode phytonnya

In [ ]:
"""mapping_umur = {
    'twenty': 20,
    '21years': 21,
    'NaN_string': np.nan,
    -5: np.nan,
    120: np.nan,
    150: np.nan
}
"""
#untuk nilai yang NaN_string, -5, 120, 150 bisa langsung di ganti dengan rata-rata umur atau di jadikan missing value, tetapi jika di jadikan missing value maka setelah ini anda akan mengganti missing value tersebut, jadi sebelum itu lebih baik  di cari rata-rata nya terlebih dahulu lalu di ganti pada mappingan ini

"mapping_umur = {\n    'twenty': 20,\n    '21years': 21,\n    'NaN_string': np.nan,\n    -5: np.nan,\n    120: np.nan,\n    150: np.nan\n}\n"

37. kita akan mencari nilai numerik nya yang aada pada umur dengan menggunakan kode phyton dibawah ini

In [ ]:
wendy_leo_saputra['umur'] = pd.to_numeric(wendy_leo_saputra['umur'], errors='coerce')
wendy_leo_saputra['umur'].mean()

np.float64(25.220588235294116)

38. selanjutnya kita mapping kan untuk memperbaiki data umur

In [ ]:
mapping_umur = {
    'twenty': 20,
    '21years': 21,
    'NaN_string': 25,
    -5: 25,
    120: 25,
    150: 25
}

39. masukan kode phyton nya dan kita replace semua nya dengan menggunakan mapping yang sudah di buat tadi

In [ ]:
wendy_leo_saputra['umur'] = wendy_leo_saputra['umur'].replace(mapping_umur)

40. sesudah itu lihat hasil nya data pada umur dan tampilkan dengan fungsi print()

In [ ]:
print("Hasil setelah pemetaan:")
print(wendy_leo_saputra['umur'].value_counts())
print(f"\nTipe data kolom 'umur' sekarang: {wendy_leo_saputra['umur'].dtype}")

Hasil setelah pemetaan:
umur
23.0    17
25.0    13
20.0    10
24.0     9
22.0     8
19.0     7
21.0     4
Name: count, dtype: int64

Tipe data kolom 'umur' sekarang: float64

41. dan kita lihat kembali pada data nya dengan memasukan kode phytonnya apakah sudah di perbaiki atau belum

In [ ]:
wendy_leo_saputra.isna().sum()
#ternyata terdapat 2 nilai yang NaN pada kolom umur

nim               0
nama              0
jurusan           0
umur              2
nilai_akhir       0
kehadiran_pct     0
tanggal_daftar    0
dtype: int64

42. dan kita akan melihat data 1 sampai 50 dengan menggunakan kode phyton ini

In [ ]:
wendy_leo_saputra.head(50)
#untuk memastika bisa menggunakan sintaks di atas dengan masukan value baris yang ingin di lihat, cara ini juga bisa di lakukan untuk tail(50)

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
0,E0001,Aldi,Pembangkit Energi,25.0,59.5,82.0,2024-05-05
1,E0002,Budi,Pembangkit Energi,20.0,84.5,99.0,2024-02-14
2,E0003,Citra,Pembangkit Energi,25.0,56.2,78.0,2024-04-29
3,E0004,Dewi,Pembangkit Energi,20.0,63.0,99.0,2024-08-02
4,E0005,Eka,Manajemen Energi,22.0,999.0,65.0,2024-03-22
5,E0006,Fajar,Pembangkit Energi,21.0,-20.0,78.0,2024-06-21
6,E0007,Gina,Informatika,19.0,70.2,150.0,2024-06-25
7,E0008,Hendra,Pembangkit Energi,25.0,56.7,-10.0,2024-10-01
8,E0009,Ika,Informatika,25.0,58.2,83.0,2024-11-17
9,E0010,Joko,Pembangkit Energi,23.0,62.7,69.0,2024-01-24
10,E0011,Kiki,Pembangkit Energi,25.0,66.6,70.0,05/02/2024
11,E0012,Lina,Informatika,22.0,66.1,82.0,2024-03-24
12,E0013,Maya,Manajemen Energi,21.0,63.4,82.0,2024-12-25
13,E0014,Nando,Pembangkit Energi,23.0,80.4,99.0,2024-05-05
14,E0015,Oki,Pembangkit Energi,22.0,70.2,100.0,2024-04-22
15,E0016,Putu,Pembangkit Energi,25.0,85.7,68.0,2024-04-27
16,E0017,Qori,Pembangkit Energi,25.0,67.6,82.0,2024-02-03
17,E0018,Rina,Pembangkit Energi,23.0,90.1,85.0,2024-04-18
18,E0019,Sari,Informatika,22.0,90.4,94.0,2024-03-24
19,E0020,Tono,Informatika,20.0,64.9,100.0,2024-10-02
20,E0021,Uli,Pembangkit Energi,24.0,78.4,90.0,2024-07-04
21,E0022,Vina,Pembangkit Energi,NaN,75.4,70.0,2024-01-25
22,E0023,Wawan,Pembangkit Energi,20.0,80.1,92.0,2024-11-01
23,E0024,Xena,Informatika,22.0,70.3,94.0,2024-09-27
24,E0025,Yudi,Pembangkit Energi,23.0,89.4,65.0,2024-12-14
25,E0026,Zara,Informatika,24.0,90.4,82.0,2024-11-24
26,E0027,Arif,Pembangkit Energi,19.0,66.7,75.0,24 Nov 2024
27,E0028,Bima,Pembangkit Energi,24.0,90.0,81.0,2024-09-13
28,E0029,Cici,Pembangkit Energi,23.0,91.5,84.0,2024-11-23
29,E0030,Dani,Pembangkit Energi,20.0,88.0,75.0,2024-10-03
30,E0031,Eros,Informatika,23.0,68.0,66.0,2024-02-27
31,E0032,Ferry,Pembangkit Energi,25.0,87.3,80.0,2024-01-30
32,E0033,Gilang,Pembangkit Energi,23.0,88.0,70.0,2024-09-05
33,E0034,Hani,Manajemen Energi,25.0,76.3,73.0,2024-03-06
34,E0035,Indra,Manajemen Energi,23.0,61.6,98.0,2024-11-06
35,E0036,Jeni,Informatika,20.0,92.2,77.0,2024-12-31
36,E0037,Kris,Manajemen Energi,22.0,94.8,88.0,2024-03-24
37,E0038,Lulu,Pembangkit Energi,19.0,64.9,69.0,2024-06-22
38,E0039,Mita,Pembangkit Energi,23.0,77.2,79.0,2024-01-04
39,E0040,Nina,Pembangkit Energi,24.0,80.2,79.0,09-17-2024
40,E0041,Omar,Informatika,25.0,88.0,97.0,2024-05-01
41,E0042,Pia,Manajemen Energi,24.0,74.4,99.0,2024-03-08
42,E0043,Rico,Pembangkit Energi,20.0,86.4,91.0,2024-04-07
43,E0044,Sinta,Manajemen Energi,19.0,81.4,87.0,2024-08-04
44,E0045,Tari,Pembangkit Energi,22.0,89.6,68.0,2024-12-10
45,E0046,Umar,Pembangkit Energi,19.0,71.1,86.0,2024-02-25
46,E0047,Vita,Manajemen Energi,20.0,62.6,93.0,2024.06.28
47,E0048,Widi,Manajemen Energi,20.0,66.1,80.0,2024-02-08
48,E0049,Xul,Pembangkit Energi,25.0,89.5,100.0,May 22 2024
49,E0050,Yosef,Pembangkit Energi,24.0,95.0,65.0,2024-02-17

43. dan untuk menampilkan data dari urut 20 sampai ke 70 bisa menggunakan kode phyton seperti ini

In [ ]:
wendy_leo_saputra.tail(50)

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
20,E0021,Uli,Pembangkit Energi,24.0,78.4,90.0,2024-07-04
21,E0022,Vina,Pembangkit Energi,NaN,75.4,70.0,2024-01-25
22,E0023,Wawan,Pembangkit Energi,20.0,80.1,92.0,2024-11-01
23,E0024,Xena,Informatika,22.0,70.3,94.0,2024-09-27
24,E0025,Yudi,Pembangkit Energi,23.0,89.4,65.0,2024-12-14
25,E0026,Zara,Informatika,24.0,90.4,82.0,2024-11-24
26,E0027,Arif,Pembangkit Energi,19.0,66.7,75.0,24 Nov 2024
27,E0028,Bima,Pembangkit Energi,24.0,90.0,81.0,2024-09-13
28,E0029,Cici,Pembangkit Energi,23.0,91.5,84.0,2024-11-23
29,E0030,Dani,Pembangkit Energi,20.0,88.0,75.0,2024-10-03
30,E0031,Eros,Informatika,23.0,68.0,66.0,2024-02-27
31,E0032,Ferry,Pembangkit Energi,25.0,87.3,80.0,2024-01-30
32,E0033,Gilang,Pembangkit Energi,23.0,88.0,70.0,2024-09-05
33,E0034,Hani,Manajemen Energi,25.0,76.3,73.0,2024-03-06
34,E0035,Indra,Manajemen Energi,23.0,61.6,98.0,2024-11-06
35,E0036,Jeni,Informatika,20.0,92.2,77.0,2024-12-31
36,E0037,Kris,Manajemen Energi,22.0,94.8,88.0,2024-03-24
37,E0038,Lulu,Pembangkit Energi,19.0,64.9,69.0,2024-06-22
38,E0039,Mita,Pembangkit Energi,23.0,77.2,79.0,2024-01-04
39,E0040,Nina,Pembangkit Energi,24.0,80.2,79.0,09-17-2024
40,E0041,Omar,Informatika,25.0,88.0,97.0,2024-05-01
41,E0042,Pia,Manajemen Energi,24.0,74.4,99.0,2024-03-08
42,E0043,Rico,Pembangkit Energi,20.0,86.4,91.0,2024-04-07
43,E0044,Sinta,Manajemen Energi,19.0,81.4,87.0,2024-08-04
44,E0045,Tari,Pembangkit Energi,22.0,89.6,68.0,2024-12-10
45,E0046,Umar,Pembangkit Energi,19.0,71.1,86.0,2024-02-25
46,E0047,Vita,Manajemen Energi,20.0,62.6,93.0,2024.06.28
47,E0048,Widi,Manajemen Energi,20.0,66.1,80.0,2024-02-08
48,E0049,Xul,Pembangkit Energi,25.0,89.5,100.0,May 22 2024
49,E0050,Yosef,Pembangkit Energi,24.0,95.0,65.0,2024-02-17
50,E0051,Zaki,Manajemen Energi,20.0,71.3,95.0,2024-04-19
51,E0052,Adel,Informatika,23.0,61.6,65.0,2024-07-18
52,E0053,Bagus,Manajemen Energi,25.0,86.4,83.0,2024-08-04
53,E0054,Cahyo,Pembangkit Energi,NaN,62.6,78.0,2024-01-30
54,E0055,Dina,Pembangkit Energi,24.0,67.5,68.0,2024-10-26
55,E0056,Edo,Pembangkit Energi,23.0,88.0,98.0,2024-03-21
56,E0057,Fauzi,Pembangkit Energi,23.0,58.2,76.0,2024-02-05
57,E0058,Gita,Pembangkit Energi,24.0,89.5,90.0,2024-03-02
58,E0059,Hadi,Informatika,23.0,78.8,70.0,2024-08-02
59,E0060,Ilham,Informatika,21.0,88.0,85.0,2024-05-02
60,E0061,Jaya,Informatika,22.0,60.2,84.0,2024-08-22
61,E0062,Kirana,Pembangkit Energi,25.0,92.4,65.0,2024-08-22
62,E0063,Lutfi,Pembangkit Energi,19.0,76.5,97.0,2024-05-15
63,E0064,Mega,Pembangkit Energi,21.0,90.2,80.0,2024-07-08
64,E0065,Nadia,Informatika,23.0,72.5,99.0,2024-12-26
65,E0066,Oleh,Pembangkit Energi,23.0,94.4,98.0,2024-01-05
66,E0067,Putri,Pembangkit Energi,24.0,59.1,82.0,2024-05-15
67,E0068,Rafi,Informatika,19.0,84.7,74.0,2024-05-19
68,E0069,Salsa,Informatika,23.0,63.4,86.0,2024-04-14
69,E0070,Tasya,Manajemen Energi,23.0,74.5,68.0,2024-02-17

44. kita akan mencari nilai numerik pada data umur dengan menggunakan kode phyton ini

In [ ]:
wendy_leo_saputra['umur'].mean() #mencari rata-rata

np.float64(22.426470588235293)

45. setelah mendapatkan nilai numerik nya kita akan memperbaiki data umur dengan menggunakan kode phyton dibawah ini

In [ ]:
wendy_leo_saputra['umur'] = wendy_leo_saputra['umur'].fillna(22) #isi dengan nilai rata-rata

46. selanjutnya kita akan melihat hasil data yang sudah di perbaiki

In [ ]:
wendy_leo_saputra.isna().sum()

nim               0
nama              0
jurusan           0
umur              0
nilai_akhir       0
kehadiran_pct     0
tanggal_daftar    0
dtype: int64

47. selanjutnya kita akan menampilkan data dari nomor 1 sampai 55 yang ada pada data dan masukan kode phytonnya

In [ ]:
wendy_leo_saputra.head(55)

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
0,E0001,Aldi,Pembangkit Energi,25.0,59.5,82.0,2024-05-05
1,E0002,Budi,Pembangkit Energi,20.0,84.5,99.0,2024-02-14
2,E0003,Citra,Pembangkit Energi,25.0,56.2,78.0,2024-04-29
3,E0004,Dewi,Pembangkit Energi,20.0,63.0,99.0,2024-08-02
4,E0005,Eka,Manajemen Energi,22.0,999.0,65.0,2024-03-22
5,E0006,Fajar,Pembangkit Energi,21.0,-20.0,78.0,2024-06-21
6,E0007,Gina,Informatika,19.0,70.2,150.0,2024-06-25
7,E0008,Hendra,Pembangkit Energi,25.0,56.7,-10.0,2024-10-01
8,E0009,Ika,Informatika,25.0,58.2,83.0,2024-11-17
9,E0010,Joko,Pembangkit Energi,23.0,62.7,69.0,2024-01-24
10,E0011,Kiki,Pembangkit Energi,25.0,66.6,70.0,05/02/2024
11,E0012,Lina,Informatika,22.0,66.1,82.0,2024-03-24
12,E0013,Maya,Manajemen Energi,21.0,63.4,82.0,2024-12-25
13,E0014,Nando,Pembangkit Energi,23.0,80.4,99.0,2024-05-05
14,E0015,Oki,Pembangkit Energi,22.0,70.2,100.0,2024-04-22
15,E0016,Putu,Pembangkit Energi,25.0,85.7,68.0,2024-04-27
16,E0017,Qori,Pembangkit Energi,25.0,67.6,82.0,2024-02-03
17,E0018,Rina,Pembangkit Energi,23.0,90.1,85.0,2024-04-18
18,E0019,Sari,Informatika,22.0,90.4,94.0,2024-03-24
19,E0020,Tono,Informatika,20.0,64.9,100.0,2024-10-02
20,E0021,Uli,Pembangkit Energi,24.0,78.4,90.0,2024-07-04
21,E0022,Vina,Pembangkit Energi,22.0,75.4,70.0,2024-01-25
22,E0023,Wawan,Pembangkit Energi,20.0,80.1,92.0,2024-11-01
23,E0024,Xena,Informatika,22.0,70.3,94.0,2024-09-27
24,E0025,Yudi,Pembangkit Energi,23.0,89.4,65.0,2024-12-14
25,E0026,Zara,Informatika,24.0,90.4,82.0,2024-11-24
26,E0027,Arif,Pembangkit Energi,19.0,66.7,75.0,24 Nov 2024
27,E0028,Bima,Pembangkit Energi,24.0,90.0,81.0,2024-09-13
28,E0029,Cici,Pembangkit Energi,23.0,91.5,84.0,2024-11-23
29,E0030,Dani,Pembangkit Energi,20.0,88.0,75.0,2024-10-03
30,E0031,Eros,Informatika,23.0,68.0,66.0,2024-02-27
31,E0032,Ferry,Pembangkit Energi,25.0,87.3,80.0,2024-01-30
32,E0033,Gilang,Pembangkit Energi,23.0,88.0,70.0,2024-09-05
33,E0034,Hani,Manajemen Energi,25.0,76.3,73.0,2024-03-06
34,E0035,Indra,Manajemen Energi,23.0,61.6,98.0,2024-11-06
35,E0036,Jeni,Informatika,20.0,92.2,77.0,2024-12-31
36,E0037,Kris,Manajemen Energi,22.0,94.8,88.0,2024-03-24
37,E0038,Lulu,Pembangkit Energi,19.0,64.9,69.0,2024-06-22
38,E0039,Mita,Pembangkit Energi,23.0,77.2,79.0,2024-01-04
39,E0040,Nina,Pembangkit Energi,24.0,80.2,79.0,09-17-2024
40,E0041,Omar,Informatika,25.0,88.0,97.0,2024-05-01
41,E0042,Pia,Manajemen Energi,24.0,74.4,99.0,2024-03-08
42,E0043,Rico,Pembangkit Energi,20.0,86.4,91.0,2024-04-07
43,E0044,Sinta,Manajemen Energi,19.0,81.4,87.0,2024-08-04
44,E0045,Tari,Pembangkit Energi,22.0,89.6,68.0,2024-12-10
45,E0046,Umar,Pembangkit Energi,19.0,71.1,86.0,2024-02-25
46,E0047,Vita,Manajemen Energi,20.0,62.6,93.0,2024.06.28
47,E0048,Widi,Manajemen Energi,20.0,66.1,80.0,2024-02-08
48,E0049,Xul,Pembangkit Energi,25.0,89.5,100.0,May 22 2024
49,E0050,Yosef,Pembangkit Energi,24.0,95.0,65.0,2024-02-17
50,E0051,Zaki,Manajemen Energi,20.0,71.3,95.0,2024-04-19
51,E0052,Adel,Informatika,23.0,61.6,65.0,2024-07-18
52,E0053,Bagus,Manajemen Energi,25.0,86.4,83.0,2024-08-04
53,E0054,Cahyo,Pembangkit Energi,22.0,62.6,78.0,2024-01-30
54,E0055,Dina,Pembangkit Energi,24.0,67.5,68.0,2024-10-26

48. dan yang terakhir kita melihat data yang terakhir dan masukan kode phyton nya

In [ ]:
wendy_leo_saputra.tail()

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
65,E0066,Oleh,Pembangkit Energi,23.0,94.4,98.0,2024-01-05
66,E0067,Putri,Pembangkit Energi,24.0,59.1,82.0,2024-05-15
67,E0068,Rafi,Informatika,19.0,84.7,74.0,2024-05-19
68,E0069,Salsa,Informatika,23.0,63.4,86.0,2024-04-14
69,E0070,Tasya,Manajemen Energi,23.0,74.5,68.0,2024-02-17

49. dan kita akan melihat info dari data tersebut masukan kode phyton nya

In [ ]:
wendy_leo_saputra.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nim             70 non-null     object
 1   nama            70 non-null     object
 2   jurusan         70 non-null     object
 3   umur            70 non-null     float64
 4   nilai_akhir     70 non-null     float64
 5   kehadiran_pct   70 non-null     float64
 6   tanggal_daftar  70 non-null     object
dtypes: float64(3), object(4)
memory usage: 4.4+ KB

50. masukan kode phyton ini untuk memindahkan data yang ada di coolab ke excel

In [ ]:
wendy_leo_saputra.to_excel("Data_mahasiswa.xlsx", index=False)

51. baru di impor data nya dari google coolab ke excel gunakan kode phyton ini

In [ ]:
from google.colab import files
files.download("Data_mahasiswa.xlsx")